#!/bin/sh /etc/rc.common

USE_PROCD=1
NAME=oscam
BIN=/usr/bin/oscam
CONF=/etc/oscam.conf

START=99
STOP=10

start_service() {
    [ -f "$CONF" ] || exit 1
    procd_open_instance
    procd_set_param command "$BIN" -c /etc/oscam
    procd_set_param respawn
    procd_set_param file "$CONF"
    procd_close_instance
}

stop_service() {
    killall -9 oscam
}

reload_service() {
    restart
}
