#!/bin/sh /etc/rc.common

USE_PROCD=1
START=95
STOP=10

SERVICE_NAME=oscam
CONFIG_DIR=/etc/oscam
BIN=/usr/bin/oscam

start_service() {
    procd_open_instance
    procd_set_param command "$BIN" -c "$CONFIG_DIR"
    procd_set_param respawn 300 5  # 自动重启策略
    procd_set_param stdout 1       # 输出日志到stdout
    procd_set_param stderr 1       # 输出错误到stderr
    procd_close_instance
}

stop_service() {
    killall "$BIN"
}
